
package com.ericsson.schemas.vas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "adminPortType", targetNamespace = "http://schemas.ericsson.com/vas/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdminPortType {


    /**
     * 
     * @param addUserRequest
     * @return
     *     returns com.ericsson.schemas.vas.AddUserResponse
     */
    @WebMethod
    @WebResult(name = "addUserResponse", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "addUserResponse")
    public AddUserResponse addUser(
        @WebParam(name = "addUserRequest", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "addUserRequest")
        AddUserRequest addUserRequest);

}
