
package com.ericsson.schemas.vas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "admin", targetNamespace = "http://schemas.ericsson.com/vas/", wsdlLocation = "file:/D:/NetBeans13/GrailsProj/crud/src/wsdl/admin.wsdl")
public class Admin
    extends Service
{

    private final static URL ADMIN_WSDL_LOCATION;
    private final static WebServiceException ADMIN_EXCEPTION;
    private final static QName ADMIN_QNAME = new QName("http://schemas.ericsson.com/vas/", "admin");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/NetBeans13/GrailsProj/crud/src/wsdl/admin.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMIN_WSDL_LOCATION = url;
        ADMIN_EXCEPTION = e;
    }

    public Admin() {
        super(__getWsdlLocation(), ADMIN_QNAME);
    }

    public Admin(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMIN_QNAME, features);
    }

    public Admin(URL wsdlLocation) {
        super(wsdlLocation, ADMIN_QNAME);
    }

    public Admin(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMIN_QNAME, features);
    }

    public Admin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Admin(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdminPortType
     */
    @WebEndpoint(name = "adminPort")
    public AdminPortType getAdminPort() {
        return super.getPort(new QName("http://schemas.ericsson.com/vas/", "adminPort"), AdminPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminPortType
     */
    @WebEndpoint(name = "adminPort")
    public AdminPortType getAdminPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.ericsson.com/vas/", "adminPort"), AdminPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMIN_EXCEPTION!= null) {
            throw ADMIN_EXCEPTION;
        }
        return ADMIN_WSDL_LOCATION;
    }

}
